hydra:
  run:
    dir: ${env:OUT}/${project.name}/${project.job}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${env:OUT}/${project.name}/${project.job}/${now:%Y-%m-%d}/${now:%H-%M-%S}

project:
  name: brainage
  job: volume
  seed: 42

trainer:
  gpus: 1
  max_epochs: 200
  benchmark: True
  deterministic: True
  #limit_train_batches: 0.1
  #limit_val_batches: 0.1
  #limit_val_batches: 0.25
  val_check_interval: 1.0
  early_stop_callback: False

model:
  norm: IN
  inputs: 1
  outputs: 2
  loss: 'l2'
  depth: 18
  use_layer: 3
  no_max_pool: False
  strides: [1,1,1,2]
  heteroscedastic: True
  position: False

optimizer:
  learning_rate: 1e-4
  weight_decay: 0.0

loader:
  batch_size: 16
  num_workers: 8

dataset:
  mode: volume
  data: ${env:DATA}/nako/interim/t1_pp_15_cropped.h5
  group: image
  info: ${env:DATA}/nako/interim/nako_age_labels.csv
  column: age
  preload: True
  fold: 0
  train: ${env:DATA}/nako/interim/keys/train${dataset.fold}.dat
  val:   ${env:DATA}/nako/interim/keys/test${dataset.fold}.dat
  #debug: ${env:DATA}/nako/interim/keys/debug1.dat
  data_augmentation: True
  #crop_size: [100, 125, 105]
  #crop_margins: [5, 5, 5]
  gamma_range: [0.7, 1.3]

