name: brainage
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.4
  - pip
  - pytorch=1.6.0 
  - torchvision=0.7.0 
  - cudatoolkit=10.2
  - pytorch-lightning==0.9.0
  - hydra-core
  - pandas
  - pyarrow=1.0.1
  - python-dotenv
  - h5py
  - matplotlib
  - wandb
  - scikit-image
  - nilearn
  - notebook
  - zarr
  - ipywidgets
  - pip:
    - batchgenerators
  