adam_beta_1: 0.9
adam_beta_2: 0.999
augmentation_flip:
- 0.5
- 0.0
- 0.0
augmentation_rotation:
- 0.1
- 0.1
- 0.1
augmentation_scale:
- 0.1
- 0.1
- 0.1
augmentation_translation:
- 10.0
- 10.0
- 10.0
b_flipout: false
b_heteroscedastic: false
base_folder: /mnt/share/raheppt1/project_data/brain/ADNI/ADNI_T1
batch_size: 8
checkpoint_dir: /mnt/share/raheppt1/tf_models/brainage/keras
default_processing: false
deterministic_conv: false
file_ext: .nii.gz
file_prefix: fcmnorm_brain_mni_ADNI_
file_suffix: _T1
image_size:
- 100
- 120
- 100
image_spacing:
- 1.5
- 1.5
- 1.5
kl_scaling: 0.001
learning_rate: 0.0001
logroot_dir: /home/raheppt1/projects/age_prediction/data/logs/keras
lr_decay: true
lr_decay_factor: 0.1
lr_decay_start_epoch: 10
max_epochs: 3000
path_info_csv: /mnt/share/raheppt1/project_data/brain/ADNI/config/ADNI_age_only.csv
path_test_csv: /mnt/share/raheppt1/project_data/brain/ADNI/config/GR_NL/NL_ADNI_T1_test_split.csv
path_training_csv: /mnt/share/raheppt1/project_data/brain/ADNI/config/GR_NL/NL_ADNI_T1_train_split0.csv
path_validation_csv: /mnt/share/raheppt1/project_data/brain/ADNI/config/GR_NL/NL_ADNI_T1_val_split0.csv
prior_scale: 1.0
run_name: ADNI_NL_bayesian
sel_optimizer: Adam
sgd_momentum: 0.0
sgd_nesterov: false
train_intensity_clamp_max: 2.0
train_intensity_clamp_min: 0.0
train_intensity_random_scale: 0.4
train_intensity_random_shift: 0.25
train_intensity_scale: 1.0
train_intensity_shift: 0.0
val_intensity_clamp_max: 2.0
val_intensity_clamp_min: 0.0
val_intensity_scale: 1.0
val_intensity_shift: 0.0
