hydra:
  run:
    dir: ${env:OUT}/${project.name}/${project.job}/${now:%Y-%m-%d}/${now:%H-%M-%S}

project:
  name: brainage
  job: 2d_slices

trainer:
  gpus: 1
  max_epochs: 100
  #default_root_dir: ./wandb
  #val_check_interval: 0.5
  benchmark: True

model:
  name: 'resnet18'
  inputs: 1
  outputs: 2
  pretrained: True
  loss: 'l2'
  heteroscedastic: True
  position: True
  #label_range: [20, 80]
  #label_step: 2.5

optimizer:
  learning_rate: 1e-4
  weight_decay: 0.0

loader:
  batch_size: 128
  num_workers: 4

dataset:
  data: ${env:DATA}/nako/interim/t1_pp_15_slices_ax2.h5
  info: ${env:DATA}/nako/interim/t1_pp_15_slices_ax2.feather
  preload: False
  slicing: 'range' 
  slices: [40,80,2]
  zoom: 3.0
  train: ${env:DATA}/nako/interim/keys/train0.dat
  val:   ${env:DATA}/nako/interim/keys/test0.dat