project:
  name: my-project
  job: Adam-32-0.001

trainer:
  gpus: 1
  max_epochs: 100
  val_check_interval: 0.25
  benchmark: True

model:
  inputs: 1
  outputs: 1

optimizer:
  learning_rate: 1e-4
  weight_decay: 0

loader:
  batch_size: 128
  num_workers: 4

dataset:
  data: /tmp/t1_pp_10_slices_ax2_image.npy
  info: ${env:DATA}/nako/interim/t1_pp_10_slices_ax2.feather
  shape: [155, 185]
  train: ${env:DATA}/nako/interim/keys/train0.dat
  val:   ${env:DATA}/nako/interim/keys/test0.dat