b_dropout: false
b_heteroscedastic: true
batch_size: 8
beta_1: 0.9
beta_2: 0.999
checkpoint_dir: /mnt/share/raheppt1/tf_models/age/keras
image_size:
- 100
- 120
- 100
image_spacing:
- 1.5
- 1.5
- 1.5
lambda_l2: 5.0e-05
learning_rate: 0.001
logroot_dir: ./logs/keras/
loss_type: negloglik
max_epochs: 3000
quantiles:
- 0.5
- 0.25
- 0.75
run_name: new_aleatoric_03b
