adam_beta_1: 0.9
adam_beta_2: 0.999
b_flipout: false
b_heteroscedastic: false
base_folder: /mnt/share/raheppt1/project_data/brain/IXI/IXI_T1/PP_IXIT1
batch_size: 8
checkpoint_dir: /mnt/share/raheppt1/tf_models/age/keras
file_ext: .nii.gz
file_prefix: fcmnorm_brain_mni_IXI
file_suffix: _T1_restore
image_size:
- 100
- 120
- 100
image_spacing:
- 1.5
- 1.5
- 1.5
kl_scaling: 0.001
learning_rate: 0.0001
logroot_dir: ./logs/keras/
lr_decay: true
lr_decay_factor: 0.1
lr_decay_start_epoch: 10
max_epochs: 3000
path_info_csv: /mnt/share/raheppt1/project_data/brain/IXI/IXI_T1/config/IXI_T1_age.csv
path_test_csv: /mnt/share/raheppt1/project_data/brain/IXI/IXI_T1/config/IXI_T1_test.csv
path_training_csv: /mnt/share/raheppt1/project_data/brain/IXI/IXI_T1/config/IXI_T1_train_split0.csv
path_validation_csv: /mnt/share/raheppt1/project_data/brain/IXI/IXI_T1/config/IXI_T1_val_split0.csv
prior_scale: 0.1
run_name: new_bayesian_09
sel_optimizer: Adam
sgd_momentum: 0.0
sgd_nesterov: false
